<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>dev.barrikeit</groupId>
    <artifactId>generic-boot-ws</artifactId>
    <version>0.1.0</version>
    <packaging>war</packaging>

    <properties>
        <!-- Project -->
        <java.version>21</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <maven.build.timestamp.format>yyyy-MM-dd'T'HH:mm:ss</maven.build.timestamp.format>
        <banner.name>${app.name}</banner.name>
        <banner.version>${app.version}</banner.version>
        <banner.build>${app.build}</banner.build>

        <!-- Spring -->
        <spring-boot.version>3.4.1</spring-boot.version>
        <spring-doc.version>2.6.0</spring-doc.version>

        <!-- Security -->
        <jwt.version>0.13.0</jwt.version>

        <!-- Logs -->
        <log4j2.version>2.25.3</log4j2.version>

        <!-- Lombok / MapStruct -->
        <lombok.version>1.18.34</lombok.version>
        <mapstruct.version>1.6.2</mapstruct.version>
        <lombok-mapstruct-binding.version>0.2.0</lombok-mapstruct-binding.version>

        <!-- Database drivers -->
        <postgresql.version>42.7.7</postgresql.version>
        <h2.version>2.3.232</h2.version>

        <!-- Utils / IO -->
        <jsoup.version>1.18.1</jsoup.version>
        <commons-io.version>2.18.0</commons-io.version>
        <apache-poi.version>5.4.0</apache-poi.version>
        <jackcess.version>4.0.7</jackcess.version>
        <pdfbox.version>3.0.3</pdfbox.version>

        <!-- dependencias solo de plugins -->
        <lombok-mapstruct-binding.version>0.2.0</lombok-mapstruct-binding.version>
        <!-- plugins -->
        <maven-compiler-plugin.version>3.14.1</maven-compiler-plugin.version>
        <maven-jar-plugin.version>3.5.0</maven-jar-plugin.version>
        <maven-war-plugin.version>3.5.0</maven-war-plugin.version>
        <maven-build-metadata-plugin.version>1.0.0</maven-build-metadata-plugin.version>
        <maven-resources-plugin.version>3.4.0</maven-resources-plugin.version>
        <spring-banner-plugin.version>1.6.0</spring-banner-plugin.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <!-- log4j-core y log4j-slf4j2-impl obtained from spring-boot -->
        <!-- hibernate-core y hibernate-validator obtained from spring-boot -->
        <!-- HikariCP obtained from spring-boot -->
        <!-- jackson-databind obtained from spring-boot -->

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-websocket</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>

        <!-- Security -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <!-- Logs -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-log4j2</artifactId>
        </dependency>

        <!-- JWT - token validation -->
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-api</artifactId>
            <version>${jwt.version}</version>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-impl</artifactId>
            <version>${jwt.version}</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-jackson</artifactId>
            <version>${jwt.version}</version>
            <scope>runtime</scope>
        </dependency>

        <!-- Lombok / Mapstruct -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${mapstruct.version}</version>
        </dependency>

        <!-- Driver JDBC (PostgreSQL, H2) -->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>${postgresql.version}</version>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>${h2.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-database-postgresql</artifactId>
        </dependency>

        <!-- Jsoup -->
        <dependency>
            <groupId>org.jsoup</groupId>
            <artifactId>jsoup</artifactId>
            <version>${jsoup.version}</version>
        </dependency>

        <!-- Dependencia commons-io para leer, escribir y modificar archivos y carpetas (FileUtils.)-->
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>${commons-io.version}</version>
        </dependency>

        <!-- Dependencia poi para leer, escribir y modificar archivos Microsoft Office (.xls, .doc, .ppt) -->
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>${apache-poi.version}</version>
        </dependency>
        <!-- Dependencia poi-ooxml aumenta la covertura de poi para archivos Microsoft Office (.xlsx, .docx) -->
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>${apache-poi.version}</version>
        </dependency>

        <!-- Dependencia jackcess para leer, escribir y modificar archivos Access (.accdb)-->
        <dependency>
            <groupId>com.healthmarketscience.jackcess</groupId>
            <artifactId>jackcess</artifactId>
            <version>${jackcess.version}</version>
        </dependency>

        <!-- Dependencia pdfbox para leer, escribir y modificar archivos pdf (.pdf)-->
        <dependency>
            <groupId>org.apache.pdfbox</groupId>
            <artifactId>pdfbox</artifactId>
            <version>${pdfbox.version}</version>
        </dependency>
    </dependencies>

    <build>
        <finalName>generic-ws</finalName>

        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>

        <plugins>
            <!-- compiler-plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${mapstruct.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>${lombok-mapstruct-binding.version}</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <compilerArg>-Amapstruct.verbose=true</compilerArg>
                        <compilerArg>-Amapstruct.defaultComponentModel=spring</compilerArg>
                    </compilerArgs>
                </configuration>
            </plugin>
            <!-- war plugins -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>${maven-war-plugin.version}</version>
                <executions>
                    <execution>
                        <id>default-war</id>
                        <goals>
                            <goal>war</goal>
                        </goals>
                        <phase>package</phase>
                    </execution>
                </executions>
                <configuration>
                    <warSourceIncludes>WEB-INF/**,META-INF/**</warSourceIncludes>
                    <failOnMissingWebXml>false</failOnMissingWebXml>
                    <outputDirectory>dist</outputDirectory>
                </configuration>
            </plugin>
            <!-- build metadata plugin -->
            <plugin>
                <groupId>dev.barrikeit.maven</groupId>
                <artifactId>build-metadata-maven-plugin</artifactId>
                <version>${maven-build-metadata-plugin.version}</version>
                <executions>
                    <execution>
                        <id>generate-build-metadata</id>
                        <phase>initialize</phase>
                        <goals>
                            <goal>generate-build-metadata</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <!-- Optional overrides -->
                    <appName>${project.build.finalName}</appName>
                    <appVersion>${project.version}</appVersion>

                    <!-- Property names -->
                    <buildIdProperty>app.build</buildIdProperty>
                    <buildTimestampProperty>app.buildTime</buildTimestampProperty>
                    <appNameProperty>app.name</appNameProperty>
                    <appVersionProperty>app.version</appVersionProperty>

                    <!-- Format options -->
                    <buildIdLength>20</buildIdLength>
                    <buildTimestampFormat>${maven.build.timestamp.format}</buildTimestampFormat>

                    <!-- Output file -->
                    <generateFile>true</generateFile>
                    <fileDirectory>${project.build.directory}/generated-sources/build-metadata</fileDirectory>
                    <fileName>build.properties</fileName>
                </configuration>
            </plugin>
            <!-- filter resources plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>${maven-resources-plugin.version}</version>
                <executions>
                    <execution>
                        <id>filter-resources</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>resources</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <filters>
                        <filter>${project.build.directory}/generated-sources/build-metadata/build.properties</filter>
                    </filters>
                    <useDefaultDelimiters>false</useDefaultDelimiters>
                    <delimiters>
                        <delimiter>@</delimiter>
                    </delimiters>
                    <resources>
                        <resource>
                            <directory>src/main/resources</directory>
                            <filtering>true</filtering>
                        </resource>
                    </resources>
                </configuration>
            </plugin>
            <!-- generate banner plugin -->
            <plugin>
                <groupId>ch.acanda.maven</groupId>
                <artifactId>spring-banner-plugin</artifactId>
                <version>${spring-banner-plugin.version}</version>
                <executions>
                    <execution>
                        <id>generate-spring-banner</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <text>${banner.name}</text>
                    <info>Version: ${banner.version} (${banner.build})</info>
                    <font>standard</font>
                    <color>default</color>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>default</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <spring.profiles.active>default</spring.profiles.active>
            </properties>
        </profile>
        <profile>
            <id>dev</id>
            <activation>
                <property>
                    <name>env</name>
                    <value>dev</value>
                </property>
            </activation>
            <properties>
                <spring.profiles.active>dev</spring.profiles.active>
            </properties>
        </profile>
        <profile>
            <id>prod</id>
            <activation>
                <property>
                    <name>env</name>
                    <value>prod</value>
                </property>
            </activation>
            <properties>
                <spring.profiles.active>prod</spring.profiles.active>
            </properties>
        </profile>
    </profiles>
</project>